### ISSUE TITLE
Setting a timeout on the API client rather than individual API function calls

### ISSUE THREAD

**Issue by Callum027** [devopsarr/prowlarr-py#11]
Hi there,

Is there a way to set a default `_request_timeout` on the `ApiClient` object, or perhaps the `Configuration` object that gets passed to it?

I'd like to set a standard timeout for all API requests I make, but from what I can see in the source and docs, the only way to set it right now is to pass `_request_timeout=<timeout>` for each request call.

This is a lot of work when making a lot of API calls so I was wondering if there was a simpler/more convenient way of doing it.

**Comment by Fuochi** [comment]
Hi @Callum027,
Sorry for my late reply. You are right, at this moment the request timeout is managed in each method.
I think your request does make sense. I'll add this to the `Configuration` object, but It could take few weeks.

**Comment by Fuochi** [comment]
closed with #14 it's now part of the `Configuration` object.
When you have both, the API call takes precedence.
