### ISSUE TITLE
Upgrade pydantic to v2

### ISSUE THREAD

**Issue by ragmehos** [devopsarr/prowlarr-py#39]
Can you please upgrade pydantic to v2?

**Comment by Fuochi** [comment]
Hi @ragmehos,
Yes, I have in plan to do that. I'll align more with the openapi generator sdk format. I'll try to do that during February

**Comment by Fuochi** [comment]
Hi @ragmehos,
sorry for the numerous references. The release pipeline broke and I had to fix it. However, the sdk should be updated, could you please have a look?
